/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hospital_mangament_system;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
import java.io.*;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
/**
 *
 * @author Adarsh Maurya
 */
public class Activity_11 extends javax.swing.JFrame {
String path="";
    /**
     * Creates new form Activity_10
     */
    public Activity_11() {
        initComponents();
        getContentPane().setBackground(new Color(153,153,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnedit = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblimage = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_specialization = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        txt_dateofjoining = new javax.swing.JTextField();
        txt_salary = new javax.swing.JTextField();
        txtcontacts = new javax.swing.JTextField();
        checksun = new javax.swing.JCheckBox();
        checkmon = new javax.swing.JCheckBox();
        checkwed = new javax.swing.JCheckBox();
        checktue = new javax.swing.JCheckBox();
        checkfri = new javax.swing.JCheckBox();
        checkthu = new javax.swing.JCheckBox();
        checksat = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        fc = new javax.swing.JFileChooser();
        btnsearch = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_empID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Nurse details");

        btnedit.setBackground(new java.awt.Color(0, 0, 0));
        btnedit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("Edit Details");
        btnedit.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btneditStateChanged(evt);
            }
        });
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(0, 0, 0));
        btnback.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnbackStateChanged(evt);
            }
        });
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add details");
        jButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton1StateChanged(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Search Details");
        jButton3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton3StateChanged(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(107)
        			.addComponent(btnback)
        			.addGap(188)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 304, GroupLayout.PREFERRED_SIZE)
        			.addGap(56)
        			.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 174, GroupLayout.PREFERRED_SIZE)
        			.addGap(37)
        			.addComponent(btnedit, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 172, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnback, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnedit, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");

        lblimage.setText("img");
        lblimage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_name.setEditable(false);
        txt_name.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Specialisation");

        txt_specialization.setEditable(false);
        txt_specialization.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_specialization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_specializationActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Date of joining");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Weekend dates");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Salary");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Contacts");

        txt_address.setEditable(false);
        txt_address.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressActionPerformed(evt);
            }
        });

        txt_dateofjoining.setEditable(false);
        txt_dateofjoining.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_dateofjoining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dateofjoiningActionPerformed(evt);
            }
        });

        txt_salary.setEditable(false);
        txt_salary.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salaryActionPerformed(evt);
            }
        });

        txtcontacts.setEditable(false);
        txtcontacts.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtcontacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontactsActionPerformed(evt);
            }
        });

        checksun.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checksun.setText("Sunday");

        checkmon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkmon.setText("Monday");

        checkwed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkwed.setText("Wednesday");
        checkwed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkwedActionPerformed(evt);
            }
        });

        checktue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checktue.setText("Tuesday");

        checkfri.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkfri.setText("Friday");

        checkthu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkthu.setText("Thursday");

        checksat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checksat.setText("Saturday");

        jButton2.setVisible(false);
        jButton2.setText("img");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnadd.setVisible(false);
        btnadd.setBackground(new java.awt.Color(0, 0, 0));
        btnadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("Add");
        btnadd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnaddStateChanged(evt);
            }
        });
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        jInternalFrame1.setVisible(false);

        jScrollPane1.setViewportView(fc);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        btnsearch.setBackground(new java.awt.Color(0, 0, 0));
        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch.setText("Search");
        btnsearch.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnsearchStateChanged(evt);
            }
        });
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnsave.setVisible(false);
        btnsave.setBackground(new java.awt.Color(0, 0, 0));
        btnsave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("Save");
        btnsave.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnsaveStateChanged(evt);
            }
        });
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("EmployeeID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(118)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(txt_name, GroupLayout.PREFERRED_SIZE, 228, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txt_specialization, GroupLayout.PREFERRED_SIZE, 343, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txt_address, GroupLayout.PREFERRED_SIZE, 343, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txt_dateofjoining, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE))
        			.addGap(14)
        			.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        			.addGap(20)
        			.addComponent(txt_empID, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
        			.addGap(300)
        			.addComponent(lblimage, GroupLayout.PREFERRED_SIZE, 180, GroupLayout.PREFERRED_SIZE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(120)
        			.addComponent(jLabel7)
        			.addGap(36)
        			.addComponent(checksun)
        			.addGap(0)
        			.addComponent(checkmon)
        			.addGap(4)
        			.addComponent(checktue)
        			.addGap(3)
        			.addComponent(checkwed)
        			.addGap(13)
        			.addComponent(checkthu)
        			.addGap(4)
        			.addComponent(checkfri)
        			.addGap(4)
        			.addComponent(checksat)
        			.addGap(221)
        			.addComponent(jButton2))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(118)
        			.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
        			.addGap(48)
        			.addComponent(txt_salary, GroupLayout.PREFERRED_SIZE, 189, GroupLayout.PREFERRED_SIZE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(118)
        			.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
        			.addGap(48)
        			.addComponent(txtcontacts, GroupLayout.PREFERRED_SIZE, 304, GroupLayout.PREFERRED_SIZE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(970)
        			.addComponent(jInternalFrame1, GroupLayout.PREFERRED_SIZE, 0, GroupLayout.PREFERRED_SIZE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(349)
        			.addComponent(btnsave, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        			.addGap(90)
        			.addComponent(btnsearch, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
        			.addGap(71)
        			.addComponent(btnadd, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(27)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        					.addGap(30)
        					.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        					.addGap(32)
        					.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        					.addGap(34)
        					.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(txt_name, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        					.addGap(28)
        					.addComponent(txt_specialization, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        					.addGap(30)
        					.addComponent(txt_address, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        					.addGap(39)
        					.addComponent(txt_dateofjoining, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        				.addComponent(txt_empID, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(30)
        					.addComponent(lblimage, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE)))
        			.addGap(10)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(checksun))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(checkmon))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(checktue))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(checkwed))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(checkthu))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(checkfri))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(checksat))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(jButton2)))
        			.addGap(15)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(14)
        					.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        				.addComponent(txt_salary, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        			.addGap(16)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(1)
        					.addComponent(txtcontacts, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)))
        			.addGap(33)
        			.addComponent(jInternalFrame1, GroupLayout.PREFERRED_SIZE, 0, GroupLayout.PREFERRED_SIZE)
        			.addGap(22)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnsave, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnsearch, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnadd, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
        			.addGap(138))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_specializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_specializationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_specializationActionPerformed

    private void txt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressActionPerformed

    private void txt_dateofjoiningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dateofjoiningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dateofjoiningActionPerformed

    private void txt_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_salaryActionPerformed

    private void txtcontactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontactsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontactsActionPerformed

    private void checkwedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkwedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkwedActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        jButton2.setVisible(true);
        btnsave.setVisible(true);
         txt_name.setEditable(true);
         txt_address.setEditable(true);
          txt_specialization.setEditable(true);
           txt_salary.setEditable(true);
            txt_dateofjoining.setEditable(true);
            txtcontacts.setEditable(true);
          txt_empID.setEditable(false);
                                  
            
    }//GEN-LAST:event_btneditActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       FileNameExtensionFilter filter= new FileNameExtensionFilter("JPEG file and PNG file","jpg","jpeg","png");
      fc.setFileFilter(filter);
      int response=fc.showOpenDialog(jInternalFrame1);
      if(response==fc.APPROVE_OPTION){
          path=fc.getSelectedFile().toString();
           ImageIcon img=new ImageIcon(path);
                  lblimage.setIcon(img);
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        new Activity_4().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed
public void clear(){
         checksun.setSelected(false);
              checkmon.setSelected(false);
              checktue.setSelected(false);
              checkwed.setSelected(false);
              checkthu.setSelected(false);
              checkfri.setSelected(false);
              checksat.setSelected(false);
                txt_name.setText("");
         txt_address.setText("");
          txt_specialization.setText("");
           txt_salary.setText("");
            txt_dateofjoining.setText("");
            txtcontacts.setText("");
            path="";
}
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
         String code="",checkcode="";String sun="A",mon="A",tue="A",wed="A",thu="A",fri="A",sat="A";
         establishconnection ob=new establishconnection();
        checkcode= "select employeeID from employee15;";
        try{
            ob.executeQuery(checkcode);
        while(ob.rs.next()){
            if(txt_empID.getText().equalsIgnoreCase(ob.rs.getString("employeeID")))
            JOptionPane.showMessageDialog(null,"EmpID already in use");
            }}
        catch(Exception e){
            
        }
       if(txt_empID.getText().equals("")||txt_name.getText().equals("")||txt_address.getText().equals(""))
            JOptionPane.showMessageDialog(null,"please enter the details");
       if(checksun.isSelected()==true)
           sun="P";
       if(checkmon.isSelected()==true)
           mon="P";
       if(checktue.isSelected()==true)
           tue="P";
       if(checkwed.isSelected()==true)
           wed="P";
       if(checkthu.isSelected()==true)
           thu="P";
       if(checkfri.isSelected()==true)
           fri="P";
       if(checksat.isSelected()==true)
           sat="P";
            code="insert into employee15 values('"+(txt_empID.getText())+"','"+txt_name.getText()+"','"+txt_specialization.getText()+"','"+txt_address.getText()+"','"+txt_dateofjoining.getText()+"','"+sun+"','"+mon+"','"+tue+"','"+wed+"','"+thu+"','"+fri+"','"+sat+"','"+txt_salary.getText()+"','"+txtcontacts.getText()+"','"+path+"','doctor');";
       System.out.println(code);
        int flag=ob.update(code);
        
        if(flag==1){
            JOptionPane.showMessageDialog(null,"added successfully");
            clear();
         }
        else if(flag==0)
                JOptionPane.showMessageDialog(null,"process failed");
       
                                  
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        String code="";String designation="";
        establishconnection ob =new establishconnection();
        if(!(txt_empID.getText().equals(""))){
            code="select * from employee15 where designation='doctor' && employeeID='"+txt_empID.getText()+"';";
            System.out.println(code);
            ob.executeQuery(code);
            try{
                while(ob.rs.next()){
                    txt_empID.setText(ob.rs.getString("employeeID"));
                    txt_name.setText(ob.rs.getString("Name"));
                    txt_specialization.setText(ob.rs.getString("specialization"));
                    txt_address.setText(ob.rs.getString("address"));
                    txt_dateofjoining.setText(""+ob.rs.getString("dateofjoin"));
                    if(ob.rs.getString("sunday").equals("P"))
                        checksun.setSelected(true);
                    if(ob.rs.getString("monday").equals("P"))
                        checkmon.setSelected(true);
                    if(ob.rs.getString("Tuesday").equals("P"))
                        checktue.setSelected(true);
                    if(ob.rs.getString("Wednesday").equals("P"))
                        checkwed.setSelected(true);
                    if(ob.rs.getString("Thursday").equals("P"))
                       checkthu.setSelected(true);
                    if(ob.rs.getString("friday").equals("P"))
                        checkfri.setSelected(true);
                   if(ob.rs.getString("Saturday").equals("P"))
                        checksat.setSelected(true);
                   txt_salary.setText(""+ob.rs.getString("salary"));
                   txtcontacts.setText(""+ob.rs.getString("contacts"));
                   String p=ob.rs.getString("img");
                   int n=p.length();
                   String np="";
                   for(int i=0;i<n;i++){
                       if(p.charAt(i)==':'){
                           np+=":\\";
                       }
                       else{
                           np+=p.charAt(i);
                       }
                   }
                   
                  ImageIcon img=new ImageIcon(np);
                  lblimage.setIcon(img);
                  designation=ob.rs.getString("designation");
                }
                if(txt_address.getText().equals(""))
                    JOptionPane.showMessageDialog(null,"Not available");
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnbackStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnbackStateChanged
        // TODO add your handling code here:
         btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
        btnedit.setBackground(Color.black);
        btnedit.setForeground(Color.white);
         btnsave.setBackground(Color.black);
        btnsave.setForeground(Color.white);
         btnsearch.setBackground(Color.black);
        btnsearch.setForeground(Color.white);
        btnback.setBackground(Color.white);
        btnback.setForeground(Color.black);
    }//GEN-LAST:event_btnbackStateChanged

    private void btneditStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btneditStateChanged
        // TODO add your handling code here:
         btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
        btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
         btnsave.setBackground(Color.black);
        btnsave.setForeground(Color.white);
         btnsearch.setBackground(Color.black);
        btnsearch.setForeground(Color.white);
        btnedit.setBackground(Color.white);
        btnedit.setForeground(Color.black);
    }//GEN-LAST:event_btneditStateChanged

    private void btnsaveStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnsaveStateChanged
        // TODO add your handling code here:
         btnedit.setBackground(Color.black);
        btnedit.setForeground(Color.white);
        btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
         btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
         btnsearch.setBackground(Color.black);
        btnsearch.setForeground(Color.white);
        btnsave.setBackground(Color.white);
        btnsave.setForeground(Color.black);
    }//GEN-LAST:event_btnsaveStateChanged

    private void btnsearchStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnsearchStateChanged
        // TODO add your handling code here:
           btnedit.setBackground(Color.black);
        btnedit.setForeground(Color.white);
        btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
         btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
         btnsave.setBackground(Color.black);
        btnsave.setForeground(Color.white);
        btnsearch.setBackground(Color.white);
        btnsearch.setForeground(Color.black);
    }//GEN-LAST:event_btnsearchStateChanged

    private void btnaddStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnaddStateChanged
        // TODO add your handling code here:
           btnedit.setBackground(Color.black);
        btnedit.setForeground(Color.white);
        btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
         btnsave.setBackground(Color.black);
        btnsave.setForeground(Color.white);
         btnsearch.setBackground(Color.black);
        btnsearch.setForeground(Color.white);
        btnadd.setBackground(Color.white);
        btnadd.setForeground(Color.black);
    }//GEN-LAST:event_btnaddStateChanged

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
        btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
        btnedit.setBackground(Color.black);
        btnedit.setForeground(Color.white);
         btnsave.setBackground(Color.black);
        btnsave.setForeground(Color.white);
         btnsearch.setBackground(Color.black);
        btnsearch.setForeground(Color.white);
        btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
          jButton3.setBackground(Color.black);
       jButton3.setForeground(Color.white);
        jButton1.setBackground(Color.black);
       jButton1.setForeground(Color.white);
    }//GEN-LAST:event_jPanel1MouseMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
        btnedit.setBackground(Color.black);
        btnedit.setForeground(Color.white);
         btnsave.setBackground(Color.black);
        btnsave.setForeground(Color.white);
         btnsearch.setBackground(Color.black);
        btnsearch.setForeground(Color.white);
        btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
    }//GEN-LAST:event_formMouseMoved

    private void jButton3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton3StateChanged
        // TODO add your handling code here:
         btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
        btnedit.setBackground(Color.black);
        btnedit.setForeground(Color.white);
         btnsave.setBackground(Color.black);
        btnsave.setForeground(Color.white);
         btnsearch.setBackground(Color.black);
        btnsearch.setForeground(Color.white);
        btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
       jButton1.setBackground(Color.black);
       jButton1.setForeground(Color.white);
         jButton3.setBackground(Color.white);
        jButton3.setForeground(Color.black);
    }//GEN-LAST:event_jButton3StateChanged

    private void jButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton1StateChanged
        // TODO add your handling code here:
         btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
        btnedit.setBackground(Color.black);
        btnedit.setForeground(Color.white);
         btnsave.setBackground(Color.black);
        btnsave.setForeground(Color.white);
         btnsearch.setBackground(Color.black);
        btnsearch.setForeground(Color.white);
        btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
        jButton3.setBackground(Color.black);
       jButton3.setForeground(Color.white);
         jButton1.setBackground(Color.white);
        jButton1.setForeground(Color.black);
    }//GEN-LAST:event_jButton1StateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        clear();
        txt_name.setEditable(false);
        txt_address.setEditable(false);
          txt_specialization.setEditable(false);
           txt_salary.setEditable(false);
            txt_dateofjoining.setEditable(false);
            txtcontacts.setEditable(false);
        txt_empID.setEditable(true);
            jButton2.setVisible(false);
            btnadd.setVisible(false);
            btnsave.setVisible(false);
            btnsearch.setVisible(true);
            txt_empID.setText("");
            ImageIcon img=new ImageIcon("");
            lblimage.setIcon(img);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         clear();
        txt_name.setEditable(true);
        txt_address.setEditable(true);
          txt_specialization.setEditable(true);
           txt_salary.setEditable(true);
            txt_dateofjoining.setEditable(true);
            txtcontacts.setEditable(true);
            jButton2.setVisible(true);
            btnadd.setVisible(true);
            btnsave.setVisible(false);
            btnsearch.setVisible(false);
            txt_empID.setText("");
            ImageIcon img=new ImageIcon("");
            lblimage.setIcon(img);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
          String code="",code1="",checkcode="";String sun="A",mon="A",tue="A",wed="A",thu="A",fri="A",sat="A";
          establishconnection ob=new establishconnection();
        checkcode= "select employeeID from employee15;";
       if(txt_empID.getText().equals("")||txt_name.getText().equals("")||txt_address.getText().equals(""))
            JOptionPane.showMessageDialog(null,"please enter the details");
       if(checksun.isSelected()==true)
           sun="P";
       if(checkmon.isSelected()==true)
           mon="P";
       if(checktue.isSelected()==true)
           tue="P";
       if(checkwed.isSelected()==true)
           wed="P";
       if(checkthu.isSelected()==true)
           thu="P";
       if(checkfri.isSelected()==true)
           fri="P";
       if(checksat.isSelected()==true)
           sat="P";
       code1="delete from employee15 where employeeID='"+txt_empID.getText()+"';";
            code="insert into employee values('"+(txt_empID.getText())+"','"+txt_name.getText()+"','"+txt_specialization.getText()+"','"+txt_address.getText()+"','"+txt_dateofjoining.getText()+"','"+sun+"','"+mon+"','"+tue+"','"+wed+"','"+thu+"','"+fri+"','"+sat+"','"+txt_salary.getText()+"','"+txtcontacts.getText()+"','"+path+"','doctor');";
       System.out.println(code);
       int flag2=ob.update(code1);
       if(flag2==1){
        int flag=ob.update(code);
        if(flag==1){
            JOptionPane.showMessageDialog(null,"Edited successfully");
            clear();
         }
        else if(flag==0||flag2==0)
                JOptionPane.showMessageDialog(null,"process failed");
       }
       else
           JOptionPane.showMessageDialog(null,"Error");
    }//GEN-LAST:event_btnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity_11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JCheckBox checkfri;
    private javax.swing.JCheckBox checkmon;
    private javax.swing.JCheckBox checksat;
    private javax.swing.JCheckBox checksun;
    private javax.swing.JCheckBox checkthu;
    private javax.swing.JCheckBox checktue;
    private javax.swing.JCheckBox checkwed;
    private javax.swing.JFileChooser fc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblimage;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_dateofjoining;
    private javax.swing.JTextField txt_empID;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_specialization;
    private javax.swing.JTextField txtcontacts;
    // End of variables declaration//GEN-END:variables
}  