package hospital_mangament_system;


import java.awt.Color;

import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adarsh Maurya
 */

public class Activity_5 extends javax.swing.JFrame {

    /**
     * Creates new form Activity_5
     */
   
    public Activity_5() {
        initComponents();
         getContentPane().setBackground(new Color(153,153,255));
         btnadd = new javax.swing.JButton();
         btnadd.setBounds(328, 623, 125, 44);
         getContentPane().add(btnadd);
         
                 btnadd.setBackground(new java.awt.Color(0, 0, 0));
                 btnadd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                 btnadd.setForeground(new java.awt.Color(255, 255, 255));
                 btnadd.setText("Add");
                 btnclear = new javax.swing.JButton();
                 btnclear.setBounds(616, 626, 106, 44);
                 getContentPane().add(btnclear);
                 
                         btnclear.setBackground(new java.awt.Color(0, 0, 0));
                         btnclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                         btnclear.setForeground(new java.awt.Color(255, 255, 255));
                         btnclear.setText("Clear");
                         btnclear.addChangeListener(new javax.swing.event.ChangeListener() {
                             public void stateChanged(javax.swing.event.ChangeEvent evt) {
                                 btnclearStateChanged(evt);
                             }
                         });
                         btnclear.addActionListener(new java.awt.event.ActionListener() {
                             public void actionPerformed(java.awt.event.ActionEvent evt) {
                                 btnclearActionPerformed(evt);
                             }
                         });
                 btnadd.addChangeListener(new javax.swing.event.ChangeListener() {
                     public void stateChanged(javax.swing.event.ChangeEvent evt) {
                         btnaddStateChanged(evt);
                     }
                 });
                 btnadd.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                         btnaddActionPerformed(evt);
                     }
                 });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_patientno = new javax.swing.JTextField();
        txt_patientname = new javax.swing.JTextField();
        txt_patientage = new javax.swing.JTextField();
        txt_patientaddress = new javax.swing.JTextField();
        txt_patientdoctor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_credit = new javax.swing.JTextField();
        txt_debit = new javax.swing.JTextField();
        txt_remaining = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        optadmit = new javax.swing.JRadioButton();
        optnotadmit = new javax.swing.JRadioButton();
        txt_bedno = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtcontacts = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtyyyy = new javax.swing.JTextField();
        txtdd = new javax.swing.JTextField();
        txtmm = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtadmsnyyyy = new javax.swing.JTextField();
        txtadmsndd = new javax.swing.JTextField();
        txtadmsnmm = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblcount = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New registration");
        setMinimumSize(new java.awt.Dimension(1500, 900));
        setPreferredSize(new java.awt.Dimension(1500, 900));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Patient No.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 90, 208, 35);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 130, 208, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Age");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 170, 208, 34);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 220, 202, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Charged Under Doctor");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 260, 202, 31);

        txt_patientno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_patientno);
        txt_patientno.setBounds(280, 90, 134, 34);

        txt_patientname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_patientname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_patientnameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_patientname);
        txt_patientname.setBounds(280, 130, 298, 34);

        txt_patientage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_patientage);
        txt_patientage.setBounds(280, 170, 80, 34);

        txt_patientaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_patientaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_patientaddressActionPerformed(evt);
            }
        });
        getContentPane().add(txt_patientaddress);
        txt_patientaddress.setBounds(280, 230, 442, 34);

        txt_patientdoctor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_patientdoctor);
        txt_patientdoctor.setBounds(280, 270, 306, 34);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Credit Amount");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 420, 208, 35);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Debit Amount");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 460, 208, 35);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Remaining Bal.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 500, 208, 35);

        txt_credit.setText("0");
        txt_credit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_credit);
        txt_credit.setBounds(280, 420, 156, 35);

        txt_debit.setText("0");
        txt_debit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_debit);
        txt_debit.setBounds(280, 460, 156, 35);

        txt_remaining.setText("0");
        txt_remaining.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_remaining);
        txt_remaining.setBounds(280, 500, 156, 35);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Date");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 330, 202, 31);

        buttonGroup1.add(optadmit);
        optadmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        optadmit.setText("Admitted");
        optadmit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                optadmitItemStateChanged(evt);
            }
        });
        getContentPane().add(optadmit);
        optadmit.setBounds(860, 140, 93, 25);

        buttonGroup1.add(optnotadmit);
        optnotadmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        optnotadmit.setSelected(true);
        optnotadmit.setText("Not Admitted");
        optnotadmit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                optnotadmitItemStateChanged(evt);
            }
        });
        getContentPane().add(optnotadmit);
        optnotadmit.setBounds(860, 170, 123, 25);

        txt_bedno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_bedno.setEnabled(false);
        getContentPane().add(txt_bedno);
        txt_bedno.setBounds(1020, 340, 146, 46);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Bed no.");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(860, 340, 139, 46);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Admission Date");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(850, 250, 139, 22);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(555, 390, 400, 230);
        txtarea_medicdetails = new javax.swing.JTextArea();
        jScrollPane1.setViewportView(txtarea_medicdetails);
        
                txtarea_medicdetails.setColumns(20);
                txtarea_medicdetails.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
                txtarea_medicdetails.setRows(5);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText(" Enter Details for Patient Registration....");

        btnback.setBackground(new java.awt.Color(0, 0, 0));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnbackStateChanged(evt);
            }
        });
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(716, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnback)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1594, 78);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 1594, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGap(0, 98, Short.MAX_VALUE)
        );
        jPanel2.setLayout(jPanel2Layout);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 770, 1594, 98);

        txtcontacts.setText("");
        txtcontacts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtcontacts);
        txtcontacts.setBounds(280, 560, 248, 43);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Contact Details");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 560, 208, 43);

        txtyyyy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtyyyy);
        txtyyyy.setBounds(400, 370, 90, 30);

        txtdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtdd);
        txtdd.setBounds(280, 370, 50, 30);

        txtmm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtmm);
        txtmm.setBounds(340, 370, 50, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("MM");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(340, 330, 40, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("YYYY");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(400, 330, 80, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("DD");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(280, 330, 40, 30);

        txtadmsnyyyy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtadmsnyyyy.setEnabled(false);
        txtadmsnyyyy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadmsnyyyyActionPerformed(evt);
            }
        });
        getContentPane().add(txtadmsnyyyy);
        txtadmsnyyyy.setBounds(1130, 280, 90, 30);

        txtadmsndd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtadmsndd.setEnabled(false);
        getContentPane().add(txtadmsndd);
        txtadmsndd.setBounds(1010, 280, 50, 30);

        txtadmsnmm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtadmsnmm.setEnabled(false);
        getContentPane().add(txtadmsnmm);
        txtadmsnmm.setBounds(1070, 280, 50, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("MM");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1070, 240, 40, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("YYYY");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1130, 240, 80, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("DD");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(1010, 240, 40, 30);

        lblcount.setBackground(new java.awt.Color(0, 0, 153));
        lblcount.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblcount.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblcount);
        lblcount.setBounds(1040, 452, 160, 140);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Total registration done  today");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(971, 397, 280, 40);

        jMenuBar2.setToolTipText("Menu Bar");
        jMenuBar2.setOpaque(false);
        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    public void newpatient(){ 
        txt_patientno.setText("");
         txt_patientname.setText("");
          txt_patientaddress.setText("");
           txt_patientdoctor.setText("");
            txtadmsnmm.setText("");
            txtadmsndd.setText("");
            txtadmsnyyyy.setText("");
             txt_credit.setText("");
              txt_debit.setText("");
               txt_remaining.setText("");
                txtmm.setText("");
                txtdd.setText("");
                txtyyyy.setText("");
                txt_patientage.setText("");
                txt_bedno.setText("");
                
                 txtarea_medicdetails.setText("");
                 optnotadmit.setSelected(true);
                 txtcontacts.setText("");
       
}
    private void optadmitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_optadmitItemStateChanged
        // TODO add your handling code here:
        txtadmsnyyyy.setEnabled(true);
        txtadmsnmm.setEnabled(true);
        txtadmsndd.setEnabled(true);
        txt_bedno.setEnabled(true);
    }//GEN-LAST:event_optadmitItemStateChanged

    private void optnotadmitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_optnotadmitItemStateChanged
        // TODO add your handling code here:
          txtadmsnyyyy.setEnabled(false);
          txtadmsnmm.setEnabled(false);
          txtadmsndd.setEnabled(false);
        txt_bedno.setEnabled(false);
    }//GEN-LAST:event_optnotadmitItemStateChanged

    private void txt_patientaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_patientaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_patientaddressActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        String checkcode="";int count=0;
         Calendar cal=Calendar.getInstance();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String today=sdf.format(cal.getTime());
       establishconnection ob=new establishconnection();
        checkcode= "select * from patient123 where checkup='"+today+"';";
        try{
            ob.executeQuery(checkcode);
        while(ob.rs.next())
            ++count;}
        catch(Exception e){
            
        }
        lblcount.setText(""+count);
        txt_patientno.setText(""+ ++count);
        
    }//GEN-LAST:event_formWindowActivated

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        newpatient();
    }//GEN-LAST:event_btnclearActionPerformed

    private void txt_patientnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_patientnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_patientnameActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        new Activity_4().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here: 
        String code="",checkcode="";int mm=0,dd=0,yyyy=0;String date="",admsndate="";int pno=0;int count=0;
        Calendar cal=Calendar.getInstance();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String today=sdf.format(cal.getTime());
      
       // else
         if(txt_patientname.getText().equals("")||txt_patientage.getText().equals("")||txt_patientaddress.getText().equals("")||txt_patientdoctor.getText().equals(""))
            JOptionPane.showMessageDialog(null,"please enter the correct details");
       pno=Integer.parseInt(txt_patientno.getText());
        if(pno<=0)
            JOptionPane.showMessageDialog(null,"please enter the correct Patient no");
        if(!txtmm.getText().equals(""))
          mm=Integer.parseInt(txtmm.getText());
        if(!txtdd.getText().equals(""))
        dd=Integer.parseInt(txtdd.getText());
        if(!txtyyyy.getText().equals(""))
        yyyy=Integer.parseInt(txtyyyy.getText());
        
              
               
        if(dd<=0||mm<=0||yyyy<=0||dd>31||mm>12||yyyy>9999){
            JOptionPane.showMessageDialog(null,"Incorrect date");
        txtdd.setText("");
     txtmm.setText("");
     txtyyyy.setText("");
     }
        else{
               date=yyyy+"-"+mm+"-"+dd;
               if(date.equals("0-0-0"))
           JOptionPane.showMessageDialog(null,"please enter the correct details");
        establishconnection ob=new establishconnection();
        checkcode= "select * from patient123 where checkup='"+today+"';";
        try{
            ob.executeQuery(checkcode);
        while(ob.rs.next())
            ++count;}
        catch(Exception e){
            
        }
        lblcount.setText(""+count);
        if(pno<=count){
            JOptionPane.showMessageDialog(null,"patient no has been registered(last registration was= reg.NO. "+count+")");
            txt_patientno.setText("");
         }
        else{
        if(optadmit.isSelected()==true){
            int admsnmm=0,admsndd=0,admsnyyyy=0;
            if(!txtadmsnmm.getText().equals(""))
             admsnmm=Integer.parseInt(txtmm.getText());
            if(!txtadmsndd.getText().equals(""))
        admsndd=Integer.parseInt(txtdd.getText());
            if(!txtadmsnyyyy.getText().equals(""))
        admsnyyyy=Integer.parseInt(txtyyyy.getText());
            admsndate=admsnyyyy+"-"+admsnmm+"-"+admsndd;
       code="insert into patient123 values("+pno+",'"+txt_patientname.getText()+"',"+Integer.parseInt(txt_patientage.getText())+",'"+txt_patientaddress.getText()+"','"+txt_patientdoctor.getText()+"','"+date+"','"+txt_credit.getText()+"','"+txt_debit.getText()+"','"+txt_remaining.getText()+"','Y','"+admsndate+"','"+txt_bedno.getText()+"',"+ txtcontacts.getText()+",'"+txtarea_medicdetails.getText()+"');";
        }
       else if(optnotadmit.isSelected()==true)
            code="insert into patient123 values("+pno+",'"+txt_patientname.getText()+"',"+Integer.parseInt(txt_patientage.getText())+",'"+txt_patientaddress.getText()+"','"+txt_patientdoctor.getText()+"','"+date+"','"+txt_credit.getText()+"','"+txt_debit.getText()+"','"+txt_remaining.getText()+"',"+"default,"+"default,"+"default,'"+txtcontacts.getText()+"','"+txtarea_medicdetails.getText()+"');";
       System.out.println(code);
        int flag=ob.update(code);
        
        if(flag==1){
            JOptionPane.showMessageDialog(null,"added successfully");
         newpatient();}
        else if(flag==0)
                JOptionPane.showMessageDialog(null,"registration failed");
        }}
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnaddStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnaddStateChanged
        // TODO add your handling code here:
        btnclear.setBackground(Color.black);
        btnclear.setForeground(Color.white);
        btnadd.setBackground(Color.white);
        btnadd.setForeground(Color.black);
    }//GEN-LAST:event_btnaddStateChanged

    private void btnclearStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnclearStateChanged
        // TODO add your handling code here:
        btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
        btnclear.setBackground(Color.white);
        btnclear.setForeground(Color.black);
    }//GEN-LAST:event_btnclearStateChanged

    private void btnbackStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnbackStateChanged
        // TODO add your handling code here:
        btnclear.setBackground(Color.black);
        btnclear.setForeground(Color.white);
        btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
        btnback.setBackground(Color.white);
        btnback.setForeground(Color.black);
    }//GEN-LAST:event_btnbackStateChanged

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
        btnclear.setBackground(Color.black);
        btnclear.setForeground(Color.white);
        btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
         btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
        // TODO add your handling code here:
        btnclear.setBackground(Color.black);
        btnclear.setForeground(Color.white);
        btnadd.setBackground(Color.black);
        btnadd.setForeground(Color.white);
         btnback.setBackground(Color.black);
        btnback.setForeground(Color.white);
    }//GEN-LAST:event_jPanel2MouseMoved

    private void txtadmsnyyyyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadmsnyyyyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadmsnyyyyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity_5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcount;
    private javax.swing.JRadioButton optadmit;
    private javax.swing.JRadioButton optnotadmit;
    private javax.swing.JTextField txt_bedno;
    private javax.swing.JTextField txt_credit;
    private javax.swing.JTextField txt_debit;
    private javax.swing.JTextField txt_patientaddress;
    private javax.swing.JTextField txt_patientage;
    private javax.swing.JTextField txt_patientdoctor;
    private javax.swing.JTextField txt_patientname;
    private javax.swing.JTextField txt_patientno;
    private javax.swing.JTextField txt_remaining;
    private javax.swing.JTextField txtadmsndd;
    private javax.swing.JTextField txtadmsnmm;
    private javax.swing.JTextField txtadmsnyyyy;
    private javax.swing.JTextArea txtarea_medicdetails;
    private javax.swing.JTextField txtcontacts;
    private javax.swing.JTextField txtdd;
    private javax.swing.JTextField txtmm;
    private javax.swing.JTextField txtyyyy;
    // End of variables declaration//GEN-END:variables
} 